### PR TITLE
Manual ease instead of fixed 250%

### PR DESCRIPTION
**Pull request by noobj2**
added a simple ease chooser + some warnings so people don't reset ease accidentally.

### CODE REVIEW

**Comment by AnKingMed** [comment]
This looks like a really cool update. In my quick test, the dialog could change values, but it always reset to 250% regardless of what you chose in the dialog

**Comment by noobj2** [comment]
> but it always reset to 250% regardless of what you chose in the dialog

fixed

**Comment by AnKingMed** [comment]
Looks great! I like the deck change as well.

**Comment by noobj2** [comment]
you might want to add your patereon and stuff to the code and update the README too.

**Comment by AnKingMed** [comment]
It's ok if it's left out. I didn't actually write this addon but the original author didn't want to port it to 2.1 and share it so I did it.  I'm just happy to help :)

**Pull request merged**
