### PR TITLE
reset-ease: correctly mark changed cards for graceful sync

### LINKED ISSUE #3: Card ease not synced
The add-on does not seem to mark the cards for sync, so the ease change is not uploaded to AnkiWeb. Realized this when looking the cards with AnkiMobile. Workaround is to manually do something with all the cards, but it gets a bit tedious. Not sure if just flagging all the cards temporarily forces a full sync of the card.

### PR DESCRIPTION
**Pull request by cyphar**
It's not recommended to write directly to the database, because Anki has
its own tracking of card changes (which allows it to do graceful
synchronisation). So simply switch to the recommended flow for updating
cards, and this solves the issue where ease factor changes weren't being
synchronised at all between devices.

Fixes: AnKingMed/Reset-Ease#3
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Alright, I've now tested that this works properly locally (I also fixed a separate bug, where we would update ease factors for cards that haven't yet been reviewed). However I don't have a scratch account on AnkiWeb to test whether this fixes the synchronisation issue (it should, since the helpers are meant to do that) but I'd appreciate it if someone could check that this solves the original bug. Otherwise this is good to go IMHO.

**Comment by cyphar** [comment]
Alright, I've now tested that this works properly both locally and after synchronisation (I also fixed a separate bug, where we would update ease factors for cards that haven't yet been reviewed). This is good to go IMHO.

**Comment by zebala** [comment]
Thank you, this worked perfectly for me, too.

> we would update ease factors for cards that haven't yet been reviewed

First I thought this bugfix didn't work, because all cards got synced, but it seems all my new cards have ease factors already; probably from an earlier usage of this add-on :) I guess in the end that shouldn't cause problems.. I hope.

**Comment by cyphar** [comment]
You're right that this will trigger a sync for cards even if the ease factor wasn't changed. I'll fix that...

**Comment by AnKingMed** [comment]
As I understand it, the manifest version is the version of the add-on, not the version of Anki. 

I've updated this on AnkiWeb. Please let me know if there are any issues

**Pull request merged**
